pipeline {
  environment {
    imagename = "orejasdetrapo/djangoapp"
    registryCredential = 'docker_hub'
    dockerImage = ''
  }
  agent any
  stages {
     stage("verify tooling"){
      steps{
        sh '''
          docker info
          docker version
          docker-compose version
          curl --version
        '''
     }
    }
    stage('Cloning Git') {
      steps {
        git([url: 'https://github.com/VictorGil-sys/Jenkins-SCM.git', branch: 'main', credentialsId: 'github'])

      }
    }
    stage('Building image') {
      steps{
          dockerImage = sh "/usr/bin/docker-compose --project-name djangoapp build -d"
      }
    }
    stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push("$BUILD_NUMBER")
             dockerImage.push('latest')
          }
        }
      }
    }
  }
}
