pipeline {
  environment {
    imagename = "orejasdetrapo/djangoapp"
    registryCredential = 'docker_hub'
    dockerImage = ''
  }
  agent any
  stages {
     stage("verify tooling"){
      steps{
        sh '''
          docker info
          docker version
          docker-compose version
          curl --version
        '''
     }
    }
    stage('Cloning Git') {
      steps {
        git([url: 'https://github.com/VictorGil-sys/Jenkins-SCM.git', branch: 'main', credentialsId: 'github'])

      }
    }
    stage('Building image') {
      steps{
       script {
          dockerImage = sh(script: "/usr/bin/docker-compose build --pull")
    
      }
     }
    } 
    stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
              dockerImage = sh(script: "/usr/bin/docker-compose push docker-django-redis-celery-main_app:$BUILD_NUMBER")
              dockerImage = sh(script: "/usr/bin/docker-compose push docker-django-redis-celery-main_app:latest")
              
              dockerImage = sh(script: "/usr/bin/docker-compose push docker-django-redis-celery-main_celery:$BUILD_NUMBER")
              dockerImage = sh(script: "/usr/bin/docker-compose push docker-django-redis-celery-main_celery:latest")

              dockerImage = sh(script: "/usr/bin/docker-compose push dockerized_django_app_backend:$BUILD_NUMBER")
              dockerImage = sh(script: "/usr/bin/docker-compose push dockerized_django_app_backend:latest")
          }
        }
      }
    }
  }
}
